# Generated by Django 5.2.4 on 2025-07-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('costo_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('macro_area', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('costo_effettivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
